### SMARTBANK BACKEND
### LOGIN
POST http://localhost:8080/iniciarsesion
content-type: application/json

{ 
    "email": "user@smartbank.com", 
    "contrasenia": "123456789"
}

### Obtener todos los usuarios
GET http://localhost:8080/clientes/enlistar

### Registrar nuevo usuario
POST http://localhost:8080/clientes/registrar
content-type: application/json

{ 
    "email": "test2@test.com",
    "dni": 22222, 
    "fechaNacimiento": "2024-07-24T15:30:00",
    "nombre": "Pepito", 
    "apellido": "Arias", 
    "telefono": 123456789, 
    "domicilio": "Domicilio Cliente", 
    "contrasenia": "abc123",
    "pais": "Colombia"
}

### Obtener cuentas "usuario"
GET http://localhost:8080/cuentas/enlistar

### Crear nueva cuenta "userID 1"
POST http://localhost:8080/cuentas/crear
content-type: application/json

{ 
    "idCliente": 2,
    "nroCuenta": 4564567, 
    "tipoCuenta": "CTACORRIENTE", 
    "saldo": 10000
}

### Obtener movimientos cuenta
GET http://localhost:8080/movimientos/enlistar

### Crear movimiento en cuenta
POST http://localhost:8080/movimientos/registrar
content-type: application/json

{ 
    "usuario": "Pepito",
    "monto": 123456, 
    "saldo": -3,
    "ctaOrigen": "1234567",
    "ctaDestino": "asd12f",
    "descripcionMovimiento": "asdfasdfsdf"
}